import type { Metadata } from "next";
import Providers from "@/redux/Provider";
import { Open_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ['latin'] })

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-opensans',
// })

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      {/* <body className={`${openSans.variable} ${robotoMono.variable} font-sans`}>{children}</body> */}
      <body className={`${robotoMono.variable} font-sans`}><Providers>{children}</Providers></body>
    </html>
  );
}
